######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 12 09:42:28 2009
######################################################################

TEMPLATE = app
TARGET =  ./bin/lab-01
OBJECTS_DIR = ./tmp/obj

# Input
HEADERS += src/contacts.h src/menu.h
SOURCES += src/contacts.c src/main.c src/menu.c
